import AuthLayout from '@/components/Layout/AuthLayout/AuthLayout';
import { ReactElement } from 'react';
import Head from 'next/head'
import React, { useState } from "react";

import styles from '@/styles/Signup.module.scss'

const Verification = () => {
  const [buttonState, setbuttonstate] = useState<boolean>(true);

  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const handleSubmit = (event:any) => {
    event.preventDefault();
    if (!code.trim()) {
      setError('code is required');
      setbuttonstate(true);
    }  else {

      setbuttonstate(false);
    }
  };
  const handleCodeChange = (event:any) => {
    setCode(event.target.value);
    setError('');
    setbuttonstate(false);
  };
    return (
    <>
    <Head>
      <title>Verification - Leagumed</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <section >
        <div className={styles.registerBlock}>
          <div className={styles.content}>
            <h1 className={styles.heading}>Welcome to the League!</h1>
            <p className={styles.description}>
            Nam consectetur lacinia odio ut finibus. Vestibulum eget consectetur velit. Curabitur varius finibus tellus, a blandit metus lacinia nec. Phasellus finibus nisi a magna dignissim sollicitudin. Etiam nisi tortor.
            </p>
           <form onSubmit={handleSubmit}>
           <div className="row">
                <div className="col">
                  <div className={`${styles.formGroup} form-group`}>
                    <label className={`${styles.label} ${styles.required}`}>code</label>
                    <input
                      type="text"
                      className={
                        !error
                          ? `${styles.control} form-control`
                          : `${styles.errorcontrol} form-control`
                      }
                      placeholder="Enter email address"
                      name="email"
                      value={code} onChange={handleCodeChange}
                    />
                          {error && <div className={styles.error}>{error}</div>} 
                  </div>
                </div>
              </div>
              <button
                type="submit"
                className={
                  buttonState ? styles.disabledsubmitbtn : styles.submitbtn
                }
                disabled={buttonState}
              >
                VERIFY CODE
              </button>
              <p className={styles.login}>Phasellus finibus nisi a magna dignissim sollicitudin. Etiam nisi tortor, pretium nec ligula et, </p>
              <p className={styles.login}>
              Didn’t Receive the Code? 
                <a href="#" target="_blank" className={styles.link}>
                RESEND CODE
                </a>
              </p>
            </form>
          </div>
        </div>
      </section>
  </>
  );
}

Verification.getLayout = function getLayout(page: ReactElement) {
  return (
      <AuthLayout>
        {page}
      </AuthLayout>
  )
}

export default Verification
